language: php

sudo: false

notifications:
  email:
    on_success: never

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.2
  - 7.3
  - 7.4

env:
  matrix:
  - TESTBENCH=^5.0  PHPUNIT=^8.5

matrix:
  exclude:

before_install:
  - composer self-update --stable --no-interaction
  - composer require orchestra/testbench:$TESTBENCH phpunit/phpunit:$PHPUNIT --no-update --no-interaction --dev

install:
  - travis_retry composer update --no-suggest --no-interaction
  - composer info

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
